spring:
  profiles:
    active: default

server:
  port: 8080
  servlet:
    context-path: /xy-inc

---


spring:
  profiles: default
  data:
    mongodb:
      uri: mongodb://localhost:27017/xyinc

---
spring:
  profiles: prod
  data:
    mongodb:
      uri: mongodb://mongodb:27017/xyinc



